version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  redis:
    image: redis:alpine

  postgres:
    build: ./compose/postgres
    image: channel_postgres
    container_name: postgres_channel_container
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file:
      - .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    image: channel_django
    container_name: django_channel_container
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
